In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
tf.set_random_seed(777) # for reproducibility

In [3]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [4]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [7]:
W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [8]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [9]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(2001):
  cost_val, hy_val, _ = sess.run(
      [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data}
  )
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22655.95 
Prediction:
 [[22.048063]
 [21.619785]
 [24.096693]
 [22.293016]
 [18.633898]]
10 Cost:  6.041784 
Prediction:
 [[155.17455]
 [181.64262]
 [181.7622 ]
 [193.98837]
 [140.6934 ]]
20 Cost:  5.813164 
Prediction:
 [[155.56952]
 [182.1321 ]
 [182.23676]
 [194.50674]
 [141.06909]]
30 Cost:  5.7920117 
Prediction:
 [[155.56291]
 [182.13885]
 [182.23572]
 [194.50719]
 [141.07661]]
40 Cost:  5.771039 
Prediction:
 [[155.55511]
 [182.14412]
 [182.23325]
 [194.50603]
 [141.08296]]
50 Cost:  5.7501407 
Prediction:
 [[155.54735]
 [182.14938]
 [182.23077]
 [194.5049 ]
 [141.08932]]
60 Cost:  5.729335 
Prediction:
 [[155.53958]
 [182.15463]
 [182.22832]
 [194.50378]
 [141.09564]]
70 Cost:  5.708634 
Prediction:
 [[155.53185]
 [182.15987]
 [182.22585]
 [194.50266]
 [141.10197]]
80 Cost:  5.688059 
Prediction:
 [[155.52414]
 [182.16512]
 [182.22343]
 [194.50156]
 [141.10828]]
90 Cost:  5.6675816 
Prediction:
 [[155.51643]
 [182.1703 ]
 [182.22096]
 [194.50043]
 [141.11455]]
100 Cost