In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

In [3]:
def min_max_scaler(data):
  numerator = data - np.min(data, 0)
  denominator = np.max(data, 0) - np.min(data, 0)
  # noise term prevents the zero division
  return numerator / (denominator + 1e-7)

In [4]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

In [5]:
# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [8]:
W = tf.Variable(tf.random_normal([4, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [9]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [10]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [11]:
# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate = 1e-5).minimize(cost)

In [12]:
# Launch the graph in a session.
with tf.Session() as sess:
  # Initializes global variables in the graph.
  sess.run(tf.global_variables_initializer())

  for step in range(101):
    _, cost_val, hy_val = sess.run(
        [train, cost, hypothesis], feed_dict = {X: x_data, Y: y_data}
    )
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.15230924 
Prediction:
 [[ 1.6346191 ]
 [ 0.06613702]
 [ 0.35008183]
 [ 0.6707252 ]
 [ 0.6113075 ]
 [ 0.61464405]
 [ 0.23171969]
 [-0.1372836 ]]
1 Cost:  0.15230872 
Prediction:
 [[ 1.634618  ]
 [ 0.06613836]
 [ 0.35008252]
 [ 0.670725  ]
 [ 0.6113076 ]
 [ 0.6146442 ]
 [ 0.23172   ]
 [-0.1372824 ]]
2 Cost:  0.15230817 
Prediction:
 [[ 1.6346169 ]
 [ 0.06613982]
 [ 0.35008317]
 [ 0.6707248 ]
 [ 0.6113077 ]
 [ 0.6146444 ]
 [ 0.23172031]
 [-0.13728127]]
3 Cost:  0.1523076 
Prediction:
 [[ 1.6346157 ]
 [ 0.06614128]
 [ 0.3500838 ]
 [ 0.67072463]
 [ 0.6113078 ]
 [ 0.6146445 ]
 [ 0.23172064]
 [-0.13728008]]
4 Cost:  0.15230703 
Prediction:
 [[ 1.6346145 ]
 [ 0.06614277]
 [ 0.35008448]
 [ 0.6707244 ]
 [ 0.61130786]
 [ 0.61464477]
 [ 0.23172095]
 [-0.13727888]]
5 Cost:  0.1523065 
Prediction:
 [[ 1.6346133 ]
 [ 0.06614411]
 [ 0.35008514]
 [ 0.6707242 ]
 [ 0.611308  ]
 [ 0.6146449 ]
 [ 0.2317213 ]
 [-0.1372777 ]]
6 Cost:  0.15230596 
Prediction:
 [[ 1.6346122 ]
 [ 0.06614557]
 [ 0.350